name: Build

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - './docs/**'

      - name: Build
        if: steps.changes.outputs.src == 'true'
        uses: ./actions/build
        with:
          revision: "pr-${{ github.event.pull_request.number }}"
          src-root: "./docs"